In [78]:
from databricks.connect import DatabricksSession
spark = DatabricksSession.builder.getOrCreate()

from pyspark.sql import Window
from pyspark.sql.functions import date_format,sum, lag, col, round, year, month

In [ ]:
# variables
# interactive widgets for catalog and schema names
dbutils.widgets.text("catalog", "nyctaxi_project_dev")
dbutils.widgets.text("silver_schema", "silver")
dbutils.widgets.text("gold_schema", "gold")

catalog = dbutils.widgets.get("catalog")
source_schema = dbutils.widgets.get("silver_schema")
target_schema = dbutils.widgets.get("gold_schema")

In [ ]:
gold_df = spark.table(f"{catalog}.{source_schema}.yellow_trips_enriched")
# display(gold_df)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[trip_id: bigint, vendor: string, pickup_datetime: timestamp, dropoff_datetime: timestamp, pickup_borough: string, pickup_zone: string, pickup_service_zone: string, dropoff_borough: string, dropoff_zone: string, dropoff_service_zone: string, passenger_count: bigint, trip_distance: double, fare_amount: double, extra: double, mta_tax: double, tip_amount: double, tolls_amount: double, improvement_surcharge: double, total_amount: double, payment_method: string, rate_name: string, congestion_surcharge: double, airport_fee: double, cbd_congestion_fee: double, ingestion_timestamp: timestamp, source_file_name: string, source_file_path: string]

In [ ]:
# calculate 3-month rolling revenue per vendor 

golf_df = spark.table(f"{catalog}.{source_schema}.yellow_trips_enriched")
vendor_month_revenue = (
    gold_df
        .withColumn("year_month", date_format("pickup_datetime", "yyyy-MM"))
        .groupBy("vendor", "year_month")
        .sum("total_amount")
        .withColumnRenamed("sum(total_amount)", "total_revenue")

)

# display(vendor_month_revenue)

# find value for rolling 3 months
w = Window.partitionBy("vendor").orderBy("year_month").rowsBetween(-2, Window.currentRow)
w_lag = Window.partitionBy("vendor").orderBy("year_month")

vendor_revenue_3m = (
    vendor_month_revenue
        .withColumn("3Mrevenue", sum("total_revenue").over(w))
        .withColumn("prev", lag("3Mrevenue", 1).over(w_lag))
        .withColumn("vs_last_month", round(100 *(col("3Mrevenue") - col("prev")) / col("prev"), 2))
        .drop("total_revenue")
)

# display(vendor_revenue_3m)

vendor_revenue_3m.write.mode("overwrite").saveAsTable(f"{catalog}.{target_schema}.vendor_3m_revenue")

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

In [ ]:
# calculate YTD revenue per vendor, compare it against the last year YTD revenue and show diff in %

from pyspark.sql.functions import lit, current_date, date_trunc, add_months, to_date, nullif

gold_df = spark.table(f"{catalog}.{source_schema}.yellow_trips_enriched")


# define a date range for YTD -> it must be between Jan 1st, current_year and current_date

ytd_start = date_trunc("year", current_date())
ytd_end = current_date()

# define a date range for YTD-1 -> it must be between last year Jan 1st and current_date -1 year

ytd_ly_start = add_months(ytd_start, -12)
ytd_ly_end = add_months(ytd_end, -12)

# filter df for only YTD values

ytd = (
    gold_df
        .filter((to_date(col("pickup_datetime")) >= ytd_start) & (to_date(col("pickup_datetime")) <= ytd_end)
                   )
        .groupBy("vendor")
        .agg(
            sum("total_amount").alias("ytd_sales")
        )
)

ly_ytd = (
    gold_df
        .filter((to_date(col("pickup_datetime")) >= ytd_ly_start) & (to_date(col("pickup_datetime")) <= ytd_ly_end)
                   )
        .groupBy("vendor")
        .agg(
            sum("total_amount").alias("ly_ytd_sales")
        )
)


final = (
    ytd.join(ly_ytd, on='vendor', how='outer')
        .fillna(0, subset=["ytd_sales", "ly_ytd_sales"])
        .withColumn("vs_ly_pct", round(100*(col("ytd_sales") - col("ly_ytd_sales")) / nullif(col("ly_ytd_sales"), lit(0)), 2)
                    )
)

final.write.mode("overwrite").saveAsTable(f"{catalog}.{target_schema}.ytd_vs_ly_ytd_revenue_vendor")

# display(final)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[vendor: string, ytd_sales: double, ly_ytd_sales: double, vs_ly_pct: double]

In [ ]:
# calculate total number of trips per month TO JFK Airport (dropoff_zone == 'JFK Airport') and FROM JFK Airport (pickup_zone == 'JFK Airport') as two separate series

# add period column to the dataset
# group by period and aggregate to_JFK trips 
# group by period and aggregate from_JFK trips

from pyspark.sql.functions import when

transform_df = (
    gold_df
        .withColumn("year_month", date_format("pickup_datetime", "yyyy-MM"))
        .withColumn("to_jfk", when(col("dropoff_zone") == "JFK Airport", lit(1)).otherwise(lit(0)))
        .withColumn("from_jfk", when(col("pickup_zone") == "JFK Airport", lit(1)).otherwise(lit(0)))
        )

jfk_trips = (
    transform_df
        .groupBy("year_month")
        .agg(
            sum("to_jfk").alias("total_trips_to_airport"),
            sum("from_jfk").alias("total_trips_from_airport")
        )
        .orderBy("year_month")
)

jfk_trips.write.mode("overwrite").saveAsTable(f"{catalog}.{target_schema}.monthly_trips_jfk")

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

In [ ]:
# calculate the most popular pickup and drop-off zones citywide (total number of trips), plus top zones ranked within each borough using window functions (rank/dense_rank)

In [ ]:
# calculate the most common pickup -> dropoff zone pairs (top 20 routes), not just zones independently
from pyspark.sql.functions import count, desc
top_routes = (
    gold_df
        .groupBy("pickup_zone", "dropoff_zone")
        .agg(
            count("trip_id").alias("total_trips")
        )
        .orderBy(desc("total_trips"))
        .limit(20)

)

top_routes.write.mode("overwrite").saveAsTable(f"{catalog}.{target_schema}.top_twenty_routes")

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

In [ ]:
# calculate revenue per passenger by month: sum(total_amount) / sum(passenger_count) per month, not a row-wise average of per-trip ratios

In [ ]:
# calculate the percentage of trips attributable to morning commute hours (7-9am), restricted to weekdays (Mon-Fri); compare against weekend mornings for contrast

from pyspark.sql.functions import dayofweek, hour, when, countDistinct, first
from pyspark.sql import Window

# add a column with an hour for each trip and add q column with a weekday

enriched_df = (
    gold_df
        .withColumns(
            {
                "hour": hour("pickup_datetime"),
                "dayofweek": dayofweek("pickup_datetime"),
                "date": to_date("pickup_datetime")
            }
        )
        .withColumn(
            "trip_type", 
                when((col("hour").isin([7,8,9])) & (col("dayofweek").isin([2,3,4,5,6])), "working_day_morning")
                .when(((col("hour").isin([7,8,9]))) & ((col("dayofweek").isin([1,7]))), "weekend_morning")
                .otherwise(lit("exclude"))
        )
        .filter((col("trip_type") == "working_day_morning") | (col("trip_type") == "weekend_morning"))
)

# calculate trips distribution and run rate 

trips_distribution = (
    enriched_df
        .groupBy("trip_type")
        .agg(
            count("*").alias("number_of_trips"),
            countDistinct("date").alias("total_days")

        )
        #.withColumn("pct_total_trips")
        .withColumn("run_rate_trips_per_day", round(col("number_of_trips") / col("total_days"),0))
)

w = Window.partitionBy()

final= (
    trips_distribution
        .withColumn("pct_total", round(100*(col("number_of_trips") / sum("number_of_trips").over(w)), 2))
)

display(final)

/Users/alehnaumovich/podyplomowe_genai_public/.venv/lib/python3.12/site-packages/pyspark/sql/connect/expressions.py:1134: UserWarning: WARN WindowExpression: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
  warnings.warn(

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[trip_type: string, number_of_trips: bigint, total_days: bigint, run_rate_trips_per_day: double, pct_total: double]

In [ ]:
# calculate total number of trips as an hour-of-day (0-23) x day-of-week heatmap: groupBy(day_of_week).pivot(hour).count() -- marginal sums give per-hour and per-day totals for free